package net.tastypommeslul.darkDupe

import org.bukkit.Material
import org.bukkit.inventory.ItemStack

object BlockedItems {
  val items: Array<ItemStack> = arrayOf(
    ItemStack(Material.NETHERITE_SCRAP),
    ItemStack(Material.NETHERITE_INGOT),
    ItemStack(Material.NETHERITE_BLOCK),
    ItemStack(Material.NETHER_STAR),
    ItemStack(Material.MACE),
    ItemStack(Material.HEAVY_CORE),
    ItemStack(Material.ENCHANTED_GOLDEN_APPLE),
    ItemStack(Material.OMINOUS_BOTTLE),
    ItemStack(Material.OMINOUS_TRIAL_KEY),
    ItemStack(Material.ELYTRA),
    ItemStack(Material.SUGAR_CANE),
    ItemStack(Material.CACTUS),
    ItemStack(Material.PINK_PETALS),
    ItemStack(Material.BAMBOO),
    ItemStack(Material.KELP),
    ItemStack(Material.NETHER_WART),
    ItemStack(Material.NETHER_WART_BLOCK),
    ItemStack(Material.SEA_PICKLE),
    ItemStack(Material.CRIMSON_STEM),
    ItemStack(Material.CRIMSON_FUNGUS),
    ItemStack(Material.WARPED_STEM),
    ItemStack(Material.WARPED_FUNGUS),
    ItemStack(Material.NETHERITE_UPGRADE_SMITHING_TEMPLATE),
    ItemStack(Material.SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE),
    ItemStack(Material.RAISER_ARMOR_TRIM_SMITHING_TEMPLATE),
    ItemStack(Material.SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE),
    ItemStack(Material.COAST_ARMOR_TRIM_SMITHING_TEMPLATE),
    ItemStack(Material.SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE),
    ItemStack(Material.BOLT_ARMOR_TRIM_SMITHING_TEMPLATE),
    ItemStack(Material.DUNE_ARMOR_TRIM_SMITHING_TEMPLATE),
    ItemStack(Material.EYE_ARMOR_TRIM_SMITHING_TEMPLATE),
    ItemStack(Material.FLOW_ARMOR_TRIM_SMITHING_TEMPLATE),
    ItemStack(Material.HOST_ARMOR_TRIM_SMITHING_TEMPLATE),
    ItemStack(Material.RIB_ARMOR_TRIM_SMITHING_TEMPLATE),
    ItemStack(Material.SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE),
    ItemStack(Material.SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE),
    ItemStack(Material.TIDE_ARMOR_TRIM_SMITHING_TEMPLATE),
    ItemStack(Material.VEX_ARMOR_TRIM_SMITHING_TEMPLATE),
    ItemStack(Material.WARD_ARMOR_TRIM_SMITHING_TEMPLATE),
    ItemStack(Material.WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE),
    ItemStack(Material.WILD_ARMOR_TRIM_SMITHING_TEMPLATE),
  )
}